import = ["~/.platform/alacritty.toml"]

[cursor]
blink_interval = 500
thickness = 0.01
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[window]
dynamic_title = true
opacity = 1
resize_increments = true

[window.dimensions]
columns = 120
lines = 40
