[cursor]
blink_interval = 500
thickness = 0.01
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
opacity = 1
resize_increments = true

[window.dimensions]
columns = 120
lines = 40

[general]
import = [
  "~/.config/alacritty/themes/themes/aura.toml",
  "~/.platform/alacritty.toml",
]
