[font]
size = 16

[font.offset]
x = 0
y = 5

[font.normal]
family = "IosevkaTermSlab Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
