[font]
size = 20

[font.offset]
x = -1
y = 0

[font.normal]
family = "IosevkaTermSlab Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
