font_family      family="IosevkaTermSlab Nerd Font"
font_size      12
modify_font cell_height 115%
modify_font cell_width 95%
# Load theme from ~/.config/kitty/Tomorrow Night.conf
include ./current-theme.conf
