# vim.ft=kitty
font_family      family="Iosevka Term Slab"
font_size        18
modify_font cell_height 115%
modify_font cell_width 100%

# Map Option+Left to send "Alt+b" (backward-word)
map alt+left send_text all \x1bb

# Map Option+Right to send "Alt+f" (forward-word)
map alt+right send_text all \x1bf

mouse_map cmd+left release grabbed,ungrabbed mouse_click_url

# Load theme from ~/.config/kitty/Tomorrow Night.conf
include ./current-theme.conf
